name: Go
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run gofmt
        run: diff -u <(echo -n) <(gofmt -s -l .)
      - name: Run tests
        run: go test -v ./src/tests
