name: Python
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r pip_requirements.txt
      - name: Run Pylint
        run: pylint src/**/*.py
      - name: Run Flake8
        run: flake8 src
      - name: Run Black
        run: black --check src
      - name: Run MyPy
        run: mypy --strict src
      - name: Run tests
        run: python -m unittest
